version: "3"
services:
  otel-collector:
    build:
      context: ../..
      dockerfile: examples/uptrace/Dockerfile
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888" # pprof extension
      #- "8888:8888" # Prometheus metrics exposed by the collector
      #- "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55680:55679" # zpages extension
      - "4317:4317" # otlp grpc
      - "55681:55681" # otlp http
